### ISSUE TITLE
How to show encrypted id/edit

### ISSUE THREAD

**Issue by stanrails** [pencil/encrypted_id#2]
I would like to send users an encrypted id/edit via email.
How can I capture the encrypted id - it seems to be only accessible via the browser.  right now I use something like http://url.com/<%=user.id %>/edit

Thanks!

**Comment by pencil** [comment]
You could either use `user.to_param` or Rails' [`url_for` helper](http://api.rubyonrails.org/classes/ActionDispatch/Routing/UrlFor.html).
